### PR TITLE
Add a Grid Warp Mode

### PR DESCRIPTION
**Pull request by cyrossignol**
This change adds an optional 9-sector-grid warp mode for mouse navigation
similar to a feature provided by some speech recognition software. It can
replace the current quaternary warp mode by adding the following to a sketch:

```cpp
void setup() {
  ...
  MouseKeys.setWarpGridSize(MOUSE_WARP_GRID_3X3);
}
```

I defined a few more warp keys to support a layout like the following:

```
     W | E | R  T    A - Cancel Warping   (Key_mouseWarpEnd)
    ---+---+---      W - Warp NW Sector   (Key_mouseWarpNW)
  A  S | D | F  G    E - Warp N Sector    (Key_mouseWarpN)
    ---+---+---      R - Warp NE Sector   (Key_mouseWarpNE)
     X | C | V  B    S - Warp E Sector    (Key_mouseWarpE)
                     D - Warp/Zoom Center (Key_mouseWarpIn)
                     F - Warp W Sector    (Key_mouseWarpW)
                     K - Warp SE Sector   (Key_mouseWarpSE)
                     C - Warp S Sector    (Key_mouseWarpS)
                     V - Warp SW Sector   (Key_mouseWarpSW)
                     T - Right Click      (Key_mouseBtnR)
                     G - Left Click       (Key_mouseBtnL)
                     B - Middle Click     (Key_mouseBtnM)
```

To illustrate, here's a screen divided into those 9 sectors:

```
  +-----------------+-----------------+-----------------+
  |  W  |  E  |  R  |                 |                 |
  |-----+-----+-----|                 |                 |
  |  S  |  D  |  F  |        E        |        R        |
  |-----+-----+-----|                 |                 |
  |  X  |  C  |  V  |                 |                 |
  +-----------------+-----------------+-----------------+
  |                 |                 |                 |
  |                 |                 |                 |
  |        S        |        D        |        F        |
  |                 |                 |                 |
  |                 |                 |                 |
  +-----------------+-----------------+-----------------+
  |                 |                 |                 |
  |                 |                 |                 |
  |        X        |        C        |        V        |
  |                 |                 |                 |
  |                 |                 |                 |
  +-----------------+-----------------+-----------------+
```

When using the layout shown above, pressing <kbd>W</kbd> warps the pointer 
into the top-left sector, and pressing <kbd>V</kbd> warps to the bottom-right
corner within that sector.

Just like with the current warp mode, the user repeats this process, jumping a
smaller distance each time within the previous sector, until he or she positions
the pointer over the target item.

### CODE REVIEW

**Comment by cyrossignol** [comment]
May also be worth mentioning that I've got some related code which adds a warp/zoom *out* key definition (so I can take step back or step sideways if I realize that I warped into the wrong cell), and which changes the warp jump to keep moving the pointer by small increments even when zoomed all the way in (to creep the pointer over the target if I missed and it's just a few px away).

These are a bit more complex than this simple PR, so I figured I'd submit them separately if needed.

**Comment by gedankenexperimenter** [comment]
When you say drag & drop doesn't work well because you clear the warp state when pressing a button, does that mean the mouse warps to the center when a mouse button is pressed? Or when it's released? I'm not clear on what else would interfere with drag & drop.

**Comment by cyrossignol** [comment]
@gedankenexperimenter Warping works at the top level, but we can't "zoom" into a cell, so it's impossible to drop an item precisely using only the warp keys. For example, I can click and drag an item to the middle of each of the 4 or 9 cells on the screen, but I can't drag it using finer movements within those cells because the plugin resets the warp state every loop iteration while holding a mouse button key.

Based on what I've tried, we can probably solve this by doing this reset on key-up instead of key-press. Need to play with it a bit more.

**Comment by cyrossignol** [comment]
I updated the branch based on @algernon's suggestions and squashed (not sure how we feel about that here). 

I moved `warpMode` to `MouseWrapper` (as `warp_grid_size`) and added a proxy method to set it from `MouseKeys` called `switchWarpMode()`. Left out the default parameter for simplicity. I'm not sure we want to encourage naming accessors with the same semantics and casing as data members...seems like this may confuse inexperienced or non-developer users when they try to understand which syntax to use for each&mdash;potentially a hot spot for simple but frustrating mistakes. 

Besides that instance, I tried to update the code changed in this branch to match the style guide. The plugin is a bit mixed in that regard, but that's a different discussion :)

**Comment by algernon** [comment]
Squashing is fine during a PR, as long as the results still make sense. In this case, they do. :)

**Comment by algernon** [comment]
I'd love if @obra could have a look at this, too.

**Comment by obra** [comment]
Thanks for the contribution! (Please don't take my pickiness here as not wanting your changes.)

First up: Please take the nice docs you wrote in the PR and add them to the plugin's README, possibly also a new example sketch for the plugin.

In terms of naming, it looks like you're using the constants 2 and 3 to define the grid size, but calling them 'MODE' - This makes the code a little bit less clear, which isn't ideal.

I'd probably call switchWarpMode  setWarpGridSize or something like that. (While being clear that it only takes the options 2 and 3) - I don't think we want to use 'quadrant' and 'nonant' (and 'nonant' isn't clearly actually a proper usage anyway)

When I first built warp mode, it had a 3x3 grid mode - I found it wasn't any faster to use than the 2x2 mode. Is your experience different? (That's not a reason not to offer the option. I'm just curious)

And yeah, the existing code doesn't match the style guide. Our goal is to improve it opportunistically as things get touched. It's not your responsibility to do so, but it's never bad :)

Since MouseKeys.cpp and MouseWrapper.cpp both include MouseWrapper.h,  I don't think there's a need to create a new .h file just for the two constants you've defined.

**Comment by cyrossignol** [comment]
Thanks for the feedback, @obra. Pickiness is good!

> When I first built warp mode, it had a 3x3 grid mode - I found it wasn't any faster to use than the 2x2 mode. Is your experience different?

I ended up replacing all of my mouse keys with this layout because I struggled to tune and adjust to the directional keys (admitting defeat&mdash;it's easier/faster for me to just grab the mouse). I found that the higher grid resolution increased my precision and reduced the number of hops. The more omni-directional warp requires less mental planning as well, at least by my perception, than the diagonal jumps, and the suggested layout sits comfortably in the sweet spot.

I know it's a personal preference, and some may have the opposite experience, so it was important to make this mode optional. No hard feelings if we ultimately want to close this because of the added complexity.

> In terms of naming, it looks like you're using the constants 2 and 3 to define the grid size, but calling them 'MODE' ... I'd probably call `switchWarpMode` `setWarpGridSize` or something like that. (While being clear that it only takes the options 2 and 3) - I don't think we want to use 'quadrant' and 'nonant'...

I tried to choose names that balance code clarity with an API that makes sense to and end user calling it from a sketch. The size of the grid is an implementation detail that's meaningful to us, but it's not a value that the user can really tweak, so I didn't want to display it in a way that might confuse someone learning to use their keyboard. We can potentially reuse this naming pattern for a warp mode added in the future that doesn't operate on a grid model (don't ask me how that would work yet!).

I do see the other side, though, and agree that switching terms is not ideal from the maintainer's point of view. Maybe `setWarpGridSize()` along with `MOUSE_WARP_GRID_2X2` and `MOUSE_WARP_GRID_3X3`?

> Since MouseKeys.cpp and MouseWrapper.cpp both include MouseWrapper.h, I don't think there's a need to create a new .h file just for the two constants you've defined.

Need to double check...it may just be my crappy C++ skills&mdash;I think I added the header to expose the constants to code outside the plugin (so we can reference them when switching modes in a sketch) and as a place to define new warp modes in the future. We only include MouseWrapper.h in the .cpp files, so unless I misunderstood, the constants would be hidden unless the user includes that header in their sketch as well. 

TODO: 
  - [ ] Update README
  - [ ] Rename "warp mode" to "warp grid size" universally
  - [ ] Investigate header file

**Comment by obra** [comment]
> I know it's a personal preference, and some may have the opposite experience, so it was important to make this mode optional. No hard feelings if we ultimately want to close this because of the added complexity.

Oh, I wasn't trying to suggest that your experience was any less valid than mine. I'd intended that as an earnest question. And your answer tells me we should probably offer both options :)

> The size of the grid is an implementation detail that's meaningful to us, but it's not a value that the user can really tweak.

Yes and no, I think. Because the size of the grid is directly tied to which movement primitives we offer, it sort of makes sense as the descriptor....though as I write that, I wonder if a 2x2 grid with only Up/Down/Left/Right primitives would actually be easier to learn than what I created in the first place.

About the header: Arduino is a little weird about what gets imported, though a header with only two constants makes my spidey-sense a bit twitchy.

**Comment by cyrossignol** [comment]
Updated [README](https://github.com/cyrossignol/Kaleidoscope-MouseKeys/tree/grid-warp-mode) and renamed "mode" to "grid size". I'm not sure where to put an example sketch or what it should contain....a full keymap layer and `setup()`? There's no *examples/* directory in this repo yet. Would it go here? Or in the main keyboardio/Kaleidoscope repo?

> About the header: Arduino is a little weird about what gets imported, though a header with only two constants makes my spidey-sense a bit twitchy.

Me too, but I can't get it to build without that, unless I don't reuse a named constant to set the default warp grid size. We could also declare the constants in MouseWrapper.h and import it into MouseKeys.h. From what @algernon said, though, it sounds like we don't want to expose that API by default.

---

> When I first built warp mode, it had a 3x3 grid mode - I found it wasn't any faster to use than the 2x2 mode. 

This made me curious...I wanted to understand more concretely whether the grid size impacts usability or if I was imagining it and wasting everyone's time, so I made [a rough little tool](https://cyrossignol.github.io/Kaleidoscope-MouseKeys/) to collect some basic measurements. For me, the denser grid does slightly reduce the number of jumps and saves a bit of time, though I'm not sure how significant these savings will be in the long run. Interestingly, I'm about a fast with a mouse except  with an ultra-wide screen. On this, warping gives an edge because of the greater distance.

> ...though as I write that, I wonder if a 2x2 grid with only Up/Down/Left/Right primitives would actually be easier to learn...

@obra heh... 

```
+---+----+---+    +-----------+    +-----------+
|   |    |   |    |           |    |  \     /  |
|   +----+   |    +---+---+---|    |   )---(   |
|   |    |   |    |   |   |   |    |  /     \  |
+---+----+---+    +-----------+    +-----------+
```

...I think you picked the best one :)

**Comment by algernon** [comment]
> There's no examples/ directory in this repo yet. Would it go here?

It should go to `examples/` here. A couple of other plugins have such examples, you can borrow ideas from there. :)

I'll have a look at the header issue tomorrow, see if I can come up with anything clever.

**Comment by cyrossignol** [comment]
@obra I see what you're saying now. This actually makes a lot of sense, and it does seem easier to learn. I imagine it could behave like so when pressing <kbd>Up</kbd><kbd>Left</kbd><kbd>Down</kbd><kbd>Right</kbd> sequentially: 

```
+---------+---------+------ ...
|         |         |   
|         |         |   
|         |         |   
+--------(2)-------(1)
|         |    |    |   
|        (3)--(4)---|   
|         |    |    |   
+---------+--------(0)----- ...
|                   |   
|...                |...

```
...for which we bisect the screen/cell only for the direction moved. It's almost a hybrid of 2x2 and 3x3 grid warping. Finding a good default layout that can ship from the factory might be tricky, though, if we want the keys to physically represent the warp directions. The current <kbd>G</kbd><kbd>B</kbd><kbd>tab</kbd><kbd>esc</kbd> cluster doesn't feel quite right for this. Couple of thoughts:

 - Place warp keys next to directional keys (<kbd>T</kbd><kbd>F</kbd><kbd>G</kbd><kbd>tab</kbd>) and move the mouse buttons. 
 - Use a modifier like <kbd>Ctrl</kbd> applied to directional keys. I haven't learned how to do this yet, so I'm not sure how feasible this approach is, and holding two modifiers isn't pleasant. 
 - Toggle warp mode on the directional keys when pressing <kbd>Key_mouseWarpEnd</kbd> (and exit warp mode when pressing a mouse button).

I just set this up with the "toggle" option using tho following layout, and I already like it: 

```
    __|E|__  T    A - Toggle Warping   E - Move/Warp Up
 A |S  D  F| G    T - Right Click      S - Move/Warp Left 
             B    G - Left Click       D - Move/Warp Down
                  B - Middle Click     F - Move/Warp Right
```
---
@algernon Thanks! I'll take a look at those plugins.

**Comment by obra** [comment]
Yeah,

At this point, even if it's better, I'd probably not enable it as the
default on the Model 01, since we've already got layout cards printed, etc
;)

**Comment by obra** [comment]
Thanks. Applied :)

**Pull request merged**
